### ISSUE TITLE
Deal with 502 from Shotgun

### ISSUE THREAD

**Issue by mikeboers** [vfxetc/sgcache#1]
From the logs

```
2015-07-15 20:30:23,394 ERROR    pid:17388 event:2026479 sgapi.core - malformed Shotgun response: '"<html>\\r\\n<head><title>502 Bad Gateway</title></head>\\r
>\\r\\n</body>\\r\\n</html>\\r\\n"'
2015-07-15 20:30:23,395 ERROR    pid:17388 event:2026479 sgcache.schema.core - error during event iteration; sleeping for 10s
Traceback (most recent call last):
  File "sgcache/schema/core.py", line 106, in watch
    for event in self.event_log.iter_events(idle_delay=idle_delay):
  File "/usr/local/vee/environments/westernx/master/lib64/python2.7/site-packages/sgevents/core.py", line 80, in iter_events
    batch = self.read(batch_size)
  File "/usr/local/vee/environments/westernx/master/lib64/python2.7/site-packages/sgevents/core.py", line 97, in read
    entities = self._find(count, filters=[('id', 'greater_than', self.max_complete_id)])
  File "/usr/local/vee/environments/westernx/master/lib64/python2.7/site-packages/sgevents/core.py", line 186, in _find
    **kwargs
  File "/usr/local/vee/environments/westernx/master/lib64/python2.7/site-packages/sgapi/core.py", line 119, in find
    return list(self.find_iter(*args, **kwargs))
  File "/usr/local/vee/environments/westernx/master/lib64/python2.7/site-packages/sgapi/core.py", line 261, in iter_sync
    for e in self.call():
  File "/usr/local/vee/environments/westernx/master/lib64/python2.7/site-packages/sgapi/core.py", line 231, in call
    entities = res['entities']
TypeError: string indices must be integers
```

In general, just check the status code. =P

**Comment by mikeboers** [comment]
Also getting lots of 504 Gateway Timeout:

```
2015-07-15 18:36:03,595 ERROR    pid:17388 event:2026432 sgapi.core - malformed Shotgun response: '"<html>\\r\\n<head><title>504 Gateway Time-out</title></head>\\r\\n<body bgcolor=\\"white\\">\\r\\n<center><h1>504 Gateway Time-out</h1></center>\\r\\n<hr><center>ngi
```
