### ISSUE TITLE
problem with install

### ISSUE THREAD

**Issue by Bezarius** [vfxetc/sgcache#4]
centos7:

```
[root@localhost sgcache]# pip install -r requirements.txt 
Collecting flask>=0.10.0 (from -r requirements.txt (line 1))
  Using cached Flask-0.10.1.tar.gz
Collecting requests>=2.7.0 (from -r requirements.txt (line 2))
  Using cached requests-2.9.1-py2.py3-none-any.whl
Collecting sqlalchemy>=1.0.0 (from -r requirements.txt (line 3))
  Using cached SQLAlchemy-1.0.12.tar.gz
Collecting pyyaml (from -r requirements.txt (line 4))
  Using cached PyYAML-3.11.tar.gz
Collecting gunicorn (from -r requirements.txt (line 6))
  Using cached gunicorn-19.4.5-py2.py3-none-any.whl
Collecting gevent (from -r requirements.txt (line 7))
  Using cached gevent-1.0.2.tar.gz
Collecting psycopg2 (from -r requirements.txt (line 9))
  Using cached psycopg2-2.6.1.tar.gz
Collecting futures (from -r requirements.txt (line 10))
  Downloading futures-3.0.5-py2-none-any.whl
Obtaining migrate from git+git@github.com:stackforge/sqlalchemy-migrate@35832555#egg=migrate (from -r requirements.txt (line 13))
  Cloning git@github.com:stackforge/sqlalchemy-migrate (to 35832555) to ./src/migrate
Warning: Permanently added the RSA host key for IP address '192.30.252.129' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
  Complete output from command git clone -q git@github.com:stackforge/sqlalchemy-migrate /home/mpavlov/sgcache/src/migrate:
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 310, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/site-packages/pip/wheel.py", line 747, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 359, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 476, in _prepare_file
    req_to_install.update_editable(not self.is_download)
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 588, in update_editable
    vcs_backend.obtain(self.source_dir)
  File "/usr/lib/python2.7/site-packages/pip/vcs/git.py", line 124, in obtain
    self.run_command(['clone', '-q', url, dest])
  File "/usr/lib/python2.7/site-packages/pip/vcs/__init__.py", line 322, in run_command
    spinner)
  File "/usr/lib/python2.7/site-packages/pip/utils/__init__.py", line 711, in call_subprocess
    ''.join(all_output) +
UnboundLocalError: local variable 'all_output' referenced before assignment
[root@localhost sgcache]# pip install -r requirements-westernx.txt 
Obtaining sgapi from git+git@github.com:westernx/sgapi#egg=sgapi (from -r requirements-westernx.txt (line 1))
  Cloning git@github.com:westernx/sgapi to ./src/sgapi
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
  Complete output from command git clone -q git@github.com:westernx/sgapi /home/mpavlov/sgcache/src/sgapi:
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 310, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/site-packages/pip/wheel.py", line 747, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 359, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 476, in _prepare_file
    req_to_install.update_editable(not self.is_download)
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 588, in update_editable
    vcs_backend.obtain(self.source_dir)
  File "/usr/lib/python2.7/site-packages/pip/vcs/git.py", line 124, in obtain
    self.run_command(['clone', '-q', url, dest])
  File "/usr/lib/python2.7/site-packages/pip/vcs/__init__.py", line 322, in run_command
    spinner)
  File "/usr/lib/python2.7/site-packages/pip/utils/__init__.py", line 711, in call_subprocess
    ''.join(all_output) +
UnboundLocalError: local variable 'all_output' referenced before assignment
```

**Comment by mikeboers** [comment]
What have you tried?

**Comment by Bezarius** [comment]
I try to start the sgcache. For that, I followed the instructions: http://sgcache.readthedocs.org/en/latest/setup.html#installation
Now I have installed all the dependencies manually.

**Comment by Bezarius** [comment]
Could you do more detailed instructions? I have little experience in the development of python and that I did not get to test your project.
